plugins:
  zh_l10n_enabled:
    default: true
    client: true
  zh_l10n_enable_weibo_logins:
    default: false
    client: true
  zh_l10n_weibo_client_id:
    default: ''
  zh_l10n_weibo_client_secret:
    default: ''
  zh_l10n_enable_renren_logins:
    default: false
    client: true
  zh_l10n_renren_client_id:
    default: ''
  zh_l10n_renren_client_secret:
    default: ''
  zh_l10n_enable_qq_logins:
    default: false
    client: true
  zh_l10n_qq_client_id:
    default: ''
  zh_l10n_qq_client_secret:
    default: ''
  zh_l10n_enable_douban_logins:
    default: false
    client: true
  zh_l10n_douban_client_id:
    default: ''
  zh_l10n_douban_client_secret:
    default: ''
